# This workflow is used to create a release

name: Create Release

on:
# Triggers the workflow on a tag push on master
  push:
    branches:
      - master

    tags:
      - v[0-9]+.[0-9]+.[0-9]+*


# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    container: python:3.6
    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: build project
        run: poetry build

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to PyPi
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN}}
        run: poetry publish
